name: flutter_app_name_changer
description: Package which helps you to rename your app
version: 0.0.1
homepage: https://github.com/qscr/flutter_app_name_changer

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  plist_parser: ^0.0.9
  xml: ^6.1.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter_app_name_changer:
  app_name: 'TestNameNew'
  android_package_name: 'ru.bala.test'
